export enum ErrorCode {
  RUN_NOT_FOUND = 'RUN_NOT_FOUND',
  REGISTRY_NOT_FOUND = 'REGISTRY_NOT_FOUND',
  AGENT_NOT_FOUND = 'AGENT_NOT_FOUND',
  CONTEXT_NOT_FOUND = 'CONTEXT_NOT_FOUND',
  FEDERATION_UPSTREAM_RATE_LIMITED = 'FEDERATION_UPSTREAM_RATE_LIMITED',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
